# Generated by Django 3.1.7 on 2021-04-03 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('limite_saque_diario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('flag_ativo', models.BooleanField()),
                ('tipo_conta', models.IntegerField()),
                ('data_criacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_transacao', models.DateTimeField()),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.conta')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.pessoa'),
        ),
    ]
