# Generated by Django 3.1.7 on 2021-04-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='id_conta',
            new_name='conta',
        ),
    ]
